/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
// flutter:
//   fonts:
//    - family:  MyFlutterApp
//      fonts:
//       - asset: fonts/Planecons.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Planecons {
  Planecons._();

  static const _kFontFam = 'Planecons';

  static const IconData flight = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData flight_land = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData flight_takeoff = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData flight_1 = IconData(0xe803, fontFamily: _kFontFam);
}
